mydjango/myApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.index,name='index'), # http://127.0.0.1:8000/ 这样的url中什么都没有 则匹配views中的index函数
    url(r'^(\d+)/(\d+)/$', views.detail), # 任意数字匹配views中的detail函数,例子：http://127.0.0.1:8000/2/3/ 页面显示detail-2-3
    url(r'^grades/$', views.grades),
    url(r'^grades2/$', views.grades2),
    url(r'^students/$', views.students),
    url(r'^grades/(\d+)$', views.gradesStudents),#(\d+)是任意数字，可以当做参数传递给views的gradesStudents方法
    url(r'^grades/(\d+)/$', views.gradesStudents),  # (\d+)是任意数字，可以当做参数传递给views的gradesStudents方法
    url(r'^grades/(\d+)/(\d+)$', views.detailStudent),
    url(r'^students/(\d+)$', views.detailStudent2),
    url(r'^addstudent/$', views.addstudent),
    url(r'^deleteStudent/$', views.deletestudent),
    url(r'^modifyStudent/$', views.modifystudent),
    url(r'^modifyStudent/modifyStudentInfo$', views.modifyStudentInfo),
    url(r'^modifyStudent/toModifyStudent/$', views.toModifyStudent),
    url(r'^deleteStudent/deleteStudentInfo$', views.deletestudentInfo),
    url(r'^addstudent2/$', views.addstudent2),
    url(r'^students2/$', views.students2),
    url(r'^students3/$', views.students3),
    url(r'^stu/(\d+)/$', views.stupage),
    url(r'^stu/(\d+)/(\d+)/$', views.detailStudent),
    url(r'^attribute/$', views.attribute),
    url(r'^get1/$', views.get1), #获取get传递的参数,网址访问：http://127.0.0.1:8000/get1?a=1&b=2&c=3
    url(r'^get2/$', views.get2), #一个键带多个值，网址访问：http://127.0.0.1:8000/get2?a=1&a=2&c=3
    url(r'^showregist$', views.showregist,name="showregist"),#显示注册界面
    url(r'^showregistforgrade$', views.showregistforgrade, name="showregistforgrade"),  # 显示注册界面
    url(r'^showregist/regist/$', views.regist),  # 注册界面
    url(r'^regist/$', views.regist),  # 注册界面
    url(r'^registgrade/$', views.registgrade),  # 注册界面
    url(r'^showresponse/$', views.showresponse),  # 注册界面
    url(r'^cookieset/$', views.cookieset),  # 注册界面
    url(r'^rediret1/$', views.rediret1),  # 注册界面
    url(r'^rediret2/$', views.rediret2),
    url(r'^main/$', views.main),
    url(r'^main/login/$', views.login),
    url(r'^showmain/$', views.showmain),
    url(r'^main/quit/$', views.quit),
    url(r'^good(\d+)/$', views.good,name="good"),
    url(r'^mainbase/$', views.mainbase),
    url(r'^upfile', views.upfile),
    url(r'^savefile$', views.savefile),
    url(r'^studentpage/(\d+)$', views.studentpage),#学生分页
    url(r'^ajaxStudent/$', views.ajaxStudent),  # ajax使用
    url(r'^studentsinfo/$', views.studentsinfo),  # ajax使用
    url(r'^edit/$', views.edit),  # 富文本使用
    url(r'^celery/$', views.celery),  # celery使用

]


# from django.urls import path
# from . import views
#
# urlpatterns = [
#     path(r'',views.index), # http://127.0.0.1:8000/ 这样的url中什么都没有 则匹配views中的index函数
#     path(r'^(\d+)/$',views.detail)
# ]

mydjango/mydjango/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from django.views import static ##新增 为了使用static中的静态文件
from django.conf import settings ##新增 为了使用static中的静态文件


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include('myApp.urls')) # 匹配myApp中的urls.py文件
    url(r'^',include(('myApp.urls','myApp'),namespace='myApp')), # 匹配myApp中的urls.py文件
    # url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'), # 为了使用static中的静态文件
]

mydjango/myApp/models.py
from django.db import models

# Create your models here.

# 对应数据库中的 grades 表
from tinymce.models import HTMLField


class Grades(models.Model):
    gname = models.CharField(max_length=20) # 对应表里字段
    gdate = models.DateTimeField()
    ggirlnum = models.IntegerField()
    gboynum = models.IntegerField()
    isDelete = models.BooleanField(default = False)
    def __str__(self):
        return "%s-%d-%d"%(self.gname,self.ggirlnum,self.gboynum)
    class Meta:
        db_table="grades"
        ordering=['id']

    #定义一个类方法创建对象,相当于构造方法
    # cls相当于self指的是Grades类
    @classmethod
    def createGrade(cls,gname,gdate,ggirlnum,gboynum,isDelete=False):
        gra=cls(gname=gname,gdate=gdate,ggirlnum=ggirlnum,gboynum=gboynum,isDelete=isDelete)
        return gra




# 自定义模型管理器Manager类
class StudentsManager(models.Manager):
    def get_queryset(self):#返回过滤后的查询结果集
        return super(StudentsManager,self).get_queryset().filter(isDelete=False)

    def get_queryset2(self,id):#返回过滤后的查询结果集
        return super(StudentsManager,self).get_queryset().filter(id=id)

    def createStudent(self,name,age,gender,contend,grade,lastT,createT,isD=False):#此方法在view中addstudent2使用
        stu=self.model()
        stu.sname=name
        stu.sage=age
        stu.sgender=gender
        stu.lastTime=lastT
        stu.createTime=createT
        stu.sgrade=grade
        return stu





# 对应数据库中的 students 表
class Students(models.Model):
    stuObj = models.Manager() # 自定义模型管理器，如果写了自定义模型管理器则objects就不能用了
    stuObj2 = StudentsManager() # 使用自定义模型管理器Manager类
    sname = models.CharField(max_length=20) # 对应表里字段
    sgender = models.BooleanField(default = True) # 性别，默认 男
    sage = models.IntegerField()
    scontend = models.CharField(max_length=20)
    sgrade = models.ForeignKey("Grades",on_delete=models.CASCADE) # 关联Grades对象表外键
    isDelete = models.BooleanField(default = False)
    lastTime = models.DateTimeField(auto_now=True)
    createTime = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.sname
    class Meta:
        db_table="students" # 表名
        ordering=['id']  # 升序
        # ordering = ['-id'] #降序

    #定义一个类方法创建对象,相当于构造方法
    # cls相当于self指的是Students类
    @classmethod
    def createStudent(cls,name,age,gender,contend,grade,lastT,createT,isD=False):
        stu=cls(sname=name,sage=age,sgender=gender,scontend=contend,sgrade=grade,lastTime=lastT,createTime=createT,isDelete=isD)
        return stu

#富文本模型类
class Text(models.Model):
    str = HTMLField()

mydjango/myApp/views.py
import os
import time

from django.conf import settings
from django.contrib.auth import logout
from django.core import paginator
from django.core.exceptions import MultipleObjectsReturned
from django.core.paginator import Paginator
from django.db.models import F
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect

from myApp.models import Grades, Students


def index(request):
    return render(request,'myApp/index.html')


def detail(request,num,num2): #num,num2 是url中的 例子：http://127.0.0.1:8000/1/2
    return HttpResponse("detail-%s-%s"%(num,num2))


def grades(request):
    # 去模板里取数据
    gradesList = Grades.objects.all()
    # 将数据传递给模板，模板再渲染页面，将渲染好的页面返回给浏览器
    # 将 gradesList 传递给grades.html中的变量grades
    return render(request,'myApp/grades.html',{"grades": gradesList}) #grades是grades.html中的变量

def grades2(request):
    # 去模板里取数据
    g = Grades.objects.filter(students__scontend__contains="我叫")
    # 将数据传递给模板，模板再渲染页面，将渲染好的页面返回给浏览器
    # 将 gradesList 传递给grades.html中的变量grades
    return HttpResponse(g)



def students(request):
    # 去模板里取数据
    studentsList = Students.stuObj2.all()
    # 将数据传递给模板，模板再渲染页面，将渲染好的页面返回给浏览器
    # 将 gradesList 传递给students.html中的变量students
    return render(request,'myApp/students.html',{"students": studentsList,
                                                 "hahayou":"我是传过去的值",
                                                 "list":["hello","nihaoma"],
                                                 "num":10,
                                                 "code":"<h1>我是测试html转义</h1>"
                                                 }
                  ) #students是students.html中的变量

def students2(request):
    # 去模板里取数据
    try:
        studentsList = Students.stuObj2.get(sgender=True)
        # 将数据传递给模板，模板再渲染页面，将渲染好的页面返回给浏览器
        # 将 gradesList 传递给students.html中的变量students
        return render(request,'myApp/students.html',{"students": studentsList}) #grades是grades.html中的变量
    except MultipleObjectsReturned:
        return HttpResponse("有多条符合条件数据")

# 显示前2个
def students3(request):
    # 去模板里取数据
    studentsList = Students.stuObj2.all()[0:2]
    # 将数据传递给模板，模板再渲染页面，将渲染好的页面返回给浏览器
    # 将 gradesList 传递给students.html中的变量students
    return render(request,'myApp/students.html',{"students": studentsList}) #grades是grades.html中的变量


# 分页显示学生
def stupage(request,page):
    # 一页显示2个,http://127.0.0.1:8000/stu/3/ 这样去访问即可
    page=int(page)
    studentsList = Students.stuObj2.all()[(page-1)*2:page*2]
    # 将数据传递给模板，模板再渲染页面，将渲染好的页面返回给浏览器
    # 将 gradesList 传递给students.html中的变量students
    return render(request, 'myApp/students.html', {"students": studentsList})  # grades是grades.html中的变量


def gradesStudents(request,num): # 点击班级现实班级中的所有学生
    grade = Grades.objects.get(pk=num)
    studentsList = grade.students_set.all()
    studentsListNew=[]
    for student in studentsList:
        if student.isDelete==False:
            studentsListNew.append(student)
    return render(request, 'myApp/students.html', {"students": studentsListNew})  # grades是grades.html中的变量

def detailStudent(request,num,num2): # 点击班级现实班级中的所有学生
    student = Students.stuObj2.get(pk=num2)
    studentsList = []
    studentsList.append(student)
    return render(request, 'myApp/studentDetail.html', {"students": studentsList})  # grades是grades.html中的变量


def detailStudent2(request,num): # 点击班级现实班级中的所有学生
    student = Students.stuObj2.get(pk=num)
    studentsList = []
    studentsList.append(student)
    return render(request, 'myApp/studentDetail.html', {"students": studentsList})  # grades是grades.html中的变量



def addstudent(request): # 点击班级现实班级中的所有学生
    grade = Grades.objects.get(pk=1)
    stu = Students.createStudent("刘德华",34,True,"wojia",grade,"2017-8-10","2017-8-11")
    stu.save()
    return HttpResponse("successful")


def deletestudent(request): # 删除学生

    return render(request, 'myApp/deletestudent.html')

def deletestudentInfo(request): # 删除学生
    id=request.POST.get("id")
    student = Students.stuObj2.get(pk=id)
    student.isDelete=True
    student.save()
    return HttpResponse("successful")


def modifystudent(request): # 修改学生信息

    return render(request, 'myApp/modifystudent.html')

def modifyStudentInfo(request): # 修改学生信息
    id=request.POST.get("id")
    stu = Students.stuObj2.get(pk=id)
    # stuList=Students.stuObj2.get_queryset()
    # for stu in stuList:
    #     if stu.
    return render(request, 'myApp/modifystudentInfo.html',{"student": stu})


def toModifyStudent(request): # 修改学生信息
    id=request.POST.get("id")
    # name=request.POST.get('name')
    gender = request.POST.get('gender')
    age = request.POST.get('age')
    gradeid = request.POST.get('grade')
    hobby = request.POST.getlist('hobby')
    stu = Students.stuObj2.get(pk=id)
    # stu.sname=name
    stu.sgender=gender
    stu.sage=age
    stu.scontend=hobby
    stu.sgrade=gradeid
    stu.save()
    return HttpResponse("successful")


def addstudent2(request): # 点击班级现实班级中的所有学生
    grade = Grades.objects.get(pk=1)
    stu = Students.stuObj2.createStudent("刘华",34,True,"wojia",grade,"2017-8-10","2017-8-11")
    stu.save()
    return HttpResponse("successful")


def attribute(request): #
    print(request.path)
    print(request.method)
    print(request.encoding)
    print(request.post)
    # e=request.get
    return HttpResponse("attribute")

def get1(request): #
    a = request.GET.get('a')
    b = request.GET.get('b')
    c = request.GET.get('c')
    # e=request.get
    return HttpResponse(a+" "+b+" "+c)

def get2(request): #
    a = request.GET.getlist('a')
    a1=a[0]
    a2=a[1]
    c = request.GET.get('c')
    # e=request.get
    return HttpResponse(a1+" "+a2+" "+c)


#POST
def showregist(request): #
    return render(request, 'myApp/regist.html')

#POST
def showregistforgrade(request): #
    return render(request, 'myApp/registgrade.html')




def regist(request): #
    #表单元素中的name属性的值就是键值
    name=request.POST.get('name')
    gender = request.POST.get('gender')
    age = request.POST.get('age')
    gradeid = request.POST.get('grade')
    hobby = request.POST.getlist('hobby')

    grade = Grades.objects.get(pk=gradeid)
    stu = Students.createStudent(name,age,gender,"I like "+hobby[0],grade,"2017-8-10","2017-8-11")
    stu.save()

    return HttpResponse(name+gender+age+hobby[0])

def registgrade(request): #
    #表单元素中的name属性的值就是键值
    name=request.POST.get('name')
    mannumber = request.POST.get('mannumber')
    girlnumber = request.POST.get('girlnumber')
    date=request.POST.get('date')

    gra = Grades.createGrade(name,date,mannumber,girlnumber)
    gra.save()
    return HttpResponse(name+mannumber+girlnumber)



#Response
def showresponse(request):
    #浏览器访问http://127.0.0.1:8000/showresponse/
    res=HttpResponse()
    res.content=b'good like this'  #这是要显示网页的内容
    print(res.content)
    print(res.charset)
    print(res.status_code)
    # print(res.conten)
    return res

#cookie
def cookieset(request):
    res = HttpResponse()
    # cookies=res.set_cookie("sunck","good")
    cookis=request.COOKIES
    res.write("<h1>"+cookis["sunck"]+"</h1>")
    return res




# 重定向
def rediret1(request):
    # return HttpResponseRedirect('/rediret2')
    return redirect('/rediret2') #这个是上面的简便写法



def rediret2(request):
    return HttpResponse("我是重定向后的视图")


#
def main(request):
    #取session
    username=request.session.get("name","游客") # 如果没取到，默认是游客

    return render(request,"myApp/main.html",{'username':username})


def login(request):
    return render(request,"myApp/login.html")


def showmain(request):
    username=request.POST.get('username')
    print(username)
    # 存储session
    request.session['name']=username
    request.session.set_expiry(10)  # 设置过期时间，单位是秒，10秒
    return redirect("/main")



def quit(request):
    #清除session
    logout(request)#推荐用这个
    #或者用这个
    # request.session.clear()
    return redirect("/main")



#反向解析
def good(request,num):
    #清除session
    logout(request)#推荐用这个
    #或者用这个
    # request.session.clear()
    return render(request,"myApp/good.html",{"num":num})

#模板继承
def mainbase(request):
    return render(request,"myApp/mainBase.html")

#上传文件
def upfile(request):
    return render(request,"myApp/upfile.html")

#保存文件
def savefile(request):
    if request.method=="POST":
        f=request.FILES["file"]
        #文件在服务器端的路径
        filePath=os.path.join(settings.MEDIA_ROOT, f.name)
        #把文件打开写到upfile中
        with open(filePath,'wb') as fp:
            #f.chunks()用于把文件流分段
            for info in f.chunks():
                fp.write(info)
        return HttpResponse("上传成功")
        # return redirect("/showregist",{"upfileresut":"sucess"} )
    else:
        return HttpResponse("请求方法不对，上传失败")




# 实现学生分页
def studentpage(request,pageid):
    # 所有学生的列表
    allList=Students.stuObj2.all()
    paginator=Paginator(allList,3)#每页3个
    page=paginator.page(pageid)
    return render(request,"myApp/studentpage.html",{"students":page})

# ajax学习
def ajaxStudent(request):
    return render(request,"myApp/ajaxStudents.html")


# ajax学习
from django.http import JsonResponse
def studentsinfo(request):
    stus=Students.stuObj2.all()
    list=[]
    for stu in stus:
        list.append([stu.sname,stu.sage])

    return JsonResponse({"data":list})







# 实现富文本
def edit(request):

    return render(request,"myApp/edit.html")

# 实现celery
def celery(request):
    # 把下面的耗时操作挪到task里面去
    # print("sucnk is a good man")
    # time.sleep(10) #模拟耗时操作，十秒钟后才能返回页面
    return render(request,"myApp/celery.html")

mydjango/templates/myApp/celery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的celery</title>
</head>
<body>
    <h1>我的celery页面</h1>
    <form action="/saveedit/" method="post">
        <textarea name="str">sunck is a good man</textarea>
        <input type="submit" value="提交"></form>
    </form>

</body>
</html>

mydjango/templates/myApp/deleteStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>删除学生</title>
</head>
<body>
    <form action="deleteStudentInfo" method="post">
        要删除学生的id:<input type="text" name="id" value=""/>
        <hr/>
        <input type="submit" value="提交">

    </form>

</body>
</html>

mydjango/templates/myApp/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的富文本</title>
<!--    不用管有没有/static/tiny_mce/tiny_mce.js这个js，会自动创建-->
    <script type="text/javascript" src="/static/tiny_mce/tiny_mce.js"></script>
    <!--            把textareas标签变成富文本-->
    <script type="text/javascript">
        tinyMCE.init({
            'mode':'textareas',
            'theme':'advanced',
            'width':800,
            'height':600
        }
        )
    </script>
</head>
<body>
    <h1>我的富文本页面</h1>
    <form action="/saveedit/" method="post">
        <textarea name="str">sunck is a good man</textarea>
        <input type="submit" value="提交"></form>
    </form>

</body>
</html>

mydjango/templates/myApp/good.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>good</title>
</head>
<body>
    good+{{num}}

</body>
</html>

mydjango/templates/myApp/grades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>班级信息</title>
</head>
<body>
    <h1>班级信息列表</h1>
    <ul>
        <!--python04,05,06-->
        {%for grade in grades%}
            <li>
                <a href="{{grade.id}}/">{{grade.gname}}</a>
<!--                地址中有/这里再加/就是追加， 若没有/就是替换-->
            </li>
        {%endfor%}
    </ul>

</body>
</html>

mydjango/templates/myApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页面</title>
<!--    测试调用静态的css-->
    <link type="text/css" href="/static/myApp/css/style.css">
<!--    测试调用静态的js-->
<!--    <script type="text/javascript" src="/static/myApp/js/sunck.js">-->
</head>
<body>
    <h1>主页面信息</h1>
    <ul>
        <!--p -->
        <li>
            <a href="/grades">grades</a><br>
            <a href="/students/">students</a><br>
<!--            分页显示学生信息，默认是第一页-->
            <a href="/studentpage/1">分页显示学生信息</a><br>
<!--            <a href="/showregist">regist</a><br>-->
            <a href="{% url 'myApp:showregist' %}">注册学学生信息</a><br>
            <a href="/deleteStudent/">删除学生</a><br>
            <a href="/modifyStudent/">修改学生信息</a><br>
            <a href="{% url 'myApp:showregistforgrade' %}">注册班级信息</a><br>
            <!--<%url'namespace:name' p1 p2%>-->
            <a href="{% url 'myApp:good' 8%}" >反向解析链接</a><br>
            <a href="/upfile">上传附件</a><br>
<!--            <a href="/good" >反向解析链接</a><br>-->

            <!--测试调用静态文件image-->
            <img src="/static/myApp/image/tree.jpg">
        </li>
    </ul>>

</body>
</html>

mydjango/templates/myApp/main.html
<!--从setting里加载static标签,就是STATIC_URL的值,下面会使用-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的</title>
<!--    引用外部css文件-->
    <link rel="stylesheet" type="text/css" href="/static/myApp/css/style.css">
<!--    引用外部js文件-->
<!--    <script type="text/javascript" src="/static/myApp/js/jquery-3.1.1.1.min.js"></script>-->
    <script type="text/javascript" src="/static/myApp/js/sunck.js"></script>

</head>
<body>
    <h1>欢迎：{{username}}</h1>
    <!--    引用外部图片-->
    <img src="/static/myApp/image/tree.jpg"/><!--    写死的-->
    <img src="{% static 'myApp/image/tree.jpg' %}"/><!--    使用第一行引入的标签加载的-->
    <a href="login">登录</a>><br>
    <a href="quit">退出登录</a>>
</body>
</html>

mydjango/templates/myApp/modifyStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改</title>
</head>
<body>
    <form action="modifyStudentInfo" method="post">
        要修改学生的id:<input type="text" name="id" value=""/>
        <hr/>
        <input type="submit" value="提交">

    </form>

</body>
</html>

mydjango/templates/myApp/modifystudentInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
    此人信息如下：<br><br>
    姓名： {{student.sname}}<br>
    性别： {{student.sgender}}<br>
    年龄： {{student.sage}}<br>
    描述： {{student.scontend}}<br><br>

    <form action="toModifyStudent/" method="post">
        姓名:<input type="text" name="age" value=""/>
        <hr/>
        性别:<input type="radio" name="gender" value="1"/>男
             <input type="radio" name="gender" value="0"/>女
        <hr/>
        年龄:<input type="text" name="age" value=""/>
        <hr/>
        班级:<input type="text" name="grade" value=""/>
        <hr/>
        爱好:<input type="checkbox" name="hobby" value="power"/>权利
             <input type="checkbox" name="hobby" value="money"/>金钱
             <input type="checkbox" name="hobby" value="boy"/>男人
             <input type="checkbox" name="hobby" value="girl"/>女人
        <hr/>
        <input type="submit" value="提交">

    </form>

</body>
</html>

mydjango/templates/myApp/regist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
    <form action="regist/" method="post">
        姓名:<input type="text" name="name" value=""/>
        <hr/>
        性别:<input type="radio" name="gender" value="1"/>男
             <input type="radio" name="gender" value="0"/>女
        <hr/>
        年龄:<input type="text" name="age" value=""/>
        <hr/>
        爱好:<input type="checkbox" name="hobby" value="power"/>权利
             <input type="checkbox" name="hobby" value="money"/>金钱
             <input type="checkbox" name="hobby" value="boy"/>男人
             <input type="checkbox" name="hobby" value="girl"/>女人
        <hr/>
        <input type="submit" value="注册">

    </form>

</body>
</html>

mydjango/templates/myApp/registgrade.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>班级添加</title>
</head>
<body>
    <form action="registgrade/" method="post">
        班级名:<input type="text" name="name" value=""/>
        <hr/>
        男生人数:<input type="text" name="mannumber" value=""/>
        <hr/>
        女生人数:<input type="text" name="girlnumber" value=""/>
        <hr/>
        开班时间:<input type="date" id="date" name="date" value="" />
        <script type="text/javascript">
            var now = new Date();
            //格式化日，如果小于9，前面补0
            var day = ("0" + now.getDate()).slice(-2);
            //格式化月，如果小于9，前面补0
            var month = ("0" + (now.getMonth() + 1)).slice(-2);
            //拼装完整日期格式
            var today = now.getFullYear()+"-"+(month)+"-"+(day) ;
            //alert(today);
            document.getElementById("date").value=(today);
        </script>
        <hr/>

        <input type="submit" value="注册">

    </form>

</body>
</html>

mydjango/templates/myApp/studentDetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学生信息</title>
</head>
<body>
    <h1>学生信息列表</h1>
    <ul>
        <!--学生列表-->
        {%for student in students%}
        <li>
            姓名： {{student.sname}}<br>
            性别： {{student.sgender}}<br>
            年龄： {{student.sage}}<br>
            描述： {{student.scontend}}<br>
        </li>
        {%endfor%}
    </ul>>

</body>
</html>

mydjango/templates/myApp/students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学生信息</title>
</head>
<body>
    <h1>学生信息列表</h1>
    <ul>
        <!--学生列表-->
        {%for student in students%}
            {% if forloop.counter|divisibleby:2 %}
                <li style="color:red">
                    <a href="{{student.id}}" style="color:red">第{{forloop.counter}}个学生：{{student.sname}}</a>-->
                </li>>
            {%else%}
                <li style="color:green">
                    <a href="{{student.id}}" style="color:green">第{{forloop.counter}}个学生：{{student.sname}}</a>-->
                </li>>
            {%endif%}
<!--        <li>-->
<!--            <a href="{{student.id}}">第{{forloop.counter}}个学生：{{student.sname}}</a>-->
<!--        </li>-->
            {%empty%}
                <h1>目前没有学生</h1>>
        {%endfor%}

        {%comment%}
            注释的内容:作用注释多行
        {%endcomment%}

        {%ifequal 1 1 %}
            语句:如果值1和值2相等则执行这个
        {%endifequal%}

        <h1>{{hahayou|upper}}</h1>>
        <h1>{{list|join:'#'}}</h1>>
        <h1>{{test|default:'没有'}}</h1>>

        <h1>传过来的数字是num={{num}}</h1>
        <h1>加法+10：num={{num|add:10}}</h1>
        <h1>减法-10：num={{num|add:-5}}</h1>
        <!--        num除1乘5-->
        <h1>乘法x5：num={% widthratio num 1 5%}</h1>
        <h1>除法/5：num={% widthratio num 5 1%}</h1><br>

        <h2>显示没有html转义：{{code|escape}}</h2>>
        <h2>显示有html转义：{{code|safe}}</h2>>
        {% autoescape off %}
            <h2>显示html转义：{{code}}</h2>>
        {% endautoescape %}

    </ul>>

</body>
</html>

mydjango/templates/myApp/upfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传文件</title>
</head>
<body>
<!--注意:from表单上传文件要加enctype="multipart/form-data"属性-->
    <form method="post" action="/savefile" enctype="multipart/form-data">
        {%csrf_token%}
        <input type="file" name="file">
        <input type="submit" name="上传">
    </form>


</body>
</html>